### PR TITLE
Support seek send and prepare any future extension

### PR DESCRIPTION
**Pull request by natir**
This issue try to solve #17 and reorganise project to support send in another directory

- [X] basic
- [X] seek
- [x] send
- [x] seeksend
- [x] documentation
- [x] test
- [x] benchmark

### CODE REVIEW

**Comment by natir** [comment]
@luizirber I have some trouble and I need your advice.

The main purpose of this pull request is to add support for bgzip but the actual avaible backend for bgzip are [bgzip](https://docs.rs/bgzip/) but BGZReader didn't implement Seek. BGZReader have his own seek interface.

We can create an issue for bgzip to request BGZReader implement Seek and/or wait another avaible backend. Did you see another solution ?

**Comment by luizirber** [comment]
sorry for missing this!

another possibility: what if we make a `niffler::send::` module, mirroring the functions (with same names) that are present in `niffler::`? This way we avoid the proliferation of `_send` functions, and also adding the `Seek` bound to the basic functions.

**Comment by natir** [comment]
No problem, :) (my twitter message it's probably more rude than what I want to say)

> another possibility: what if we make a niffler::send:: module, mirroring the functions (with same names) that are present in niffler::? This way we avoid the proliferation of _send functions, and also adding the Seek bound to the basic functions.

I like this idea. Keep similar API (`from_path`, `get_reader`, `get_writer`, `sniff`, `to_path`) between different modules to support seek or send is a very good idea! But I see two trouble with this approach:
- multiplication of module en combination of functionality we probably need a seek_send module
- code duplication, but we can probably use some rust black magic to make some transtyping and avoid code duplication when we want.

```
// module send

pub fn sniff<'a>(
    in_stream: Box<dyn io::Read + Send + 'a>,
) -> Result<(Box<dyn io::Read + Send + 'a>, compression::Format), Error> {
    let in_stream_without_send = /*some rust black magic*/
    let (out_stream, compression_format) = niffler::sniff(in_stream);
   let out_stream_with_send = /*some rust black magic*/

    Ok((out_stream_with_send, compression_format))
}
```

But this trouble doesn't seem very large for me.

Finally you didn't answer to my question about Seek in bgzip crates.

**Comment by natir** [comment]
@luizirber I think with this pull request the niffler version 2.3.0 is ready.

Switch from version 2.2.0 to 2.3.0 would be very easy for the classic user, but peoples who want to use `Send` or `Seek` object can do it now.

Badly `bgzip` couldn't be full support because we haven't available backend with `std::io::Seek` support actually but this support could be added very easily in the future.

I open to any modification and suggest, if you see typo in the documentation please correct them directly.

About minimum_rust_version I think the test is broken by a dependency of our dependency, so maybe we need to bump to a new rust minimal version or be more restrictive on dependency version.

I didn't put any example about usage of `send`, `seek` or `seeksend` module in the main page example did you think we need to have it?

**Comment by luizirber** [comment]
> @luizirber I think with this pull request the niffler version 2.3.0 is ready.
> 
> Switch from version 2.2.0 to 2.3.0 would be very easy for the classic user, but peoples who want to use `Send` or `Seek` object can do it now.

This is great, thanks @natir!

> Badly `bgzip` couldn't be full support because we haven't available backend with `std::io::Seek` support actually but this support could be added very easily in the future.
> 
> I open to any modification and suggest, if you see typo in the documentation please correct them directly.
> 
> About minimum_rust_version I think the test is broken by a dependency of our dependency, so maybe we need to bump to a new rust minimal version or be more restrictive on dependency version.

I'll check that and make a release

> I didn't put any example about usage of `send`, `seek` or `seeksend` module in the main page example did you think we need to have it?

I think we can add a note that if the default functions don't work, you can use the `send`/`seek`/`seeksend` variations.

>     * multiplication of module en combination of functionality we probably need a seek_send module
>     * code duplication, but we can probably use some rust black magic to make some transtyping and avoid code duplication when we want.

I think it is easier to have duplication now and figure out a macro/some other feature to avoid it later, 

> Finally you didn't answer to my question about Seek in bgzip crates.

I didn't answer because I misread `Seek` as `Send`, sorry if this made things confusing for you :sweat:
I guess the best solution is to make a PR for `Seek` in `bgzip`, but I don't know how much work that would be...

(I'm already using the `Send` version with `needletail`, so thanks again for that!)

**Review by luizirber — APPROVED** [review]

**Comment by luizirber** [comment]
I also added a new check on CI for compiling for webassembly (with no compression/gzip), because that's what I use =]

**Pull request merged**
