### PR TITLE
Remote cfg_if! macro dependency

### PR DESCRIPTION
**Pull request by dralley**
The standard builtin cfg!() macro is actually cleaner and also less code.

### CODE REVIEW

**Comment by dralley** [comment]
`cfg_if!` would be more useful if there were multiple possible implementations, but since the implementations are only switched on or off, it doesn't add any value over the builtin version.

https://doc.rust-lang.org/std/macro.cfg.html

**Review by natir — APPROVED** [review]

**Comment by natir** [comment]
@luizirber  if it's ok for you can merge

**Comment by luizirber** [comment]
Thanks for the PR, @dralley!

The main issue is that `cfg!` [requires all codepaths to be valid](https://doc.rust-lang.org/std/macro.cfg.html), and this is what is making the tests fail in CI. You can get the same failures locally by running `cargo build --no-default-features`, when none of `bz2`/`flate2`/`xz2` crates are available and so there are compilation errors.

**Comment by dralley** [comment]
@luizirber Fair point - it appears this is not as easy as I initially though, or at least the benefits will not be as great once finished.

I'll close this, and if there's a better way I may reopen, but I don't immediately see one.

**Comment by natir** [comment]
Thank for your interest on this project @dralley

**Pull request closed without merging**
