### PR TITLE
Add feature to allow user to select features of backend

### PR DESCRIPTION
**Pull request by natir**
To address issue #53 I add many features, to let user access to backend features.

It's seems the only way to let user access to backend features, I didn't see any way to do it automatically. 

I choose to use our feature name as prefix in place of package name but we can change this if you want @luizirber.

Todo:
- [x] Add documentation to explain this features

### CODE REVIEW

**Comment by natir** [comment]
Before write documentation I prefer wait your review on this idea @luizirber

**Comment by natir** [comment]
@luizirber Can I have your opinion on this pull request ?

**Review by luizirber — APPROVED** [review]
It is an explosion of feature names, but I don't see a better way of exposing it all... we might want to flip around defaults based on #55, but otherwise LGTM!

**Comment by luizirber** [comment]
Once we are at MSRV 1.60 this could be useful too: https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#new-syntax-for-cargo-features

**Comment by natir** [comment]
I add an issue to keep in mind when we bump MSRV to 1.60 we can remove all these features.

@luizirber If it's ok for you please merge.

**Pull request merged**
